apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: kubernetes-bootcamp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
        version: v1
    spec:
      containers:
      - name: my-pod
        image: gcr.io/google-samples/kubernetes-bootcamp:v1
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
        version: 1.0.3
    spec:
      containers:
      - name: nginx
        image: gcr.io/myproject-212609/nginx-test
        ports:
        - containerPort: 8080
