apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: my-ingress
spec:
  rules:
  - http:
      paths:
      - path: /api
        backend:
          serviceName: kubernetes-bootcamp
          servicePort: 8080
      - path: /nginx
        backend:
          serviceName: my-nginx-service
          servicePort: 80
